# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: glimmer-dsl-css 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "glimmer-dsl-css".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["AndyMaleh".freeze]
  s.date = "2020-06-14"
  s.description = "Glimmer DSL for CSS (Cascading Style Sheets)".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/glimmer-dsl-css.rb",
    "lib/glimmer/config.rb",
    "lib/glimmer/css/rule.rb",
    "lib/glimmer/css/style_sheet.rb",
    "lib/glimmer/dsl/css/css_expression.rb",
    "lib/glimmer/dsl/css/dsl.rb",
    "lib/glimmer/dsl/css/dynamic_property_expression.rb",
    "lib/glimmer/dsl/css/property_expression.rb",
    "lib/glimmer/dsl/css/pv_expression.rb",
    "lib/glimmer/dsl/css/rule_expression.rb",
    "lib/glimmer/dsl/css/s_expression.rb",
    "lib/glimmer/dsl/engine.rb",
    "lib/glimmer/dsl/expression.rb",
    "lib/glimmer/dsl/expression_handler.rb",
    "lib/glimmer/dsl/opal/dsl.rb",
    "lib/glimmer/dsl/opal/label_expression.rb",
    "lib/glimmer/dsl/opal/property_expression.rb",
    "lib/glimmer/dsl/opal/shell_expression.rb",
    "lib/glimmer/dsl/parent_expression.rb",
    "lib/glimmer/dsl/static_expression.rb",
    "lib/glimmer/dsl/top_level_expression.rb",
    "lib/glimmer/dsl/xml/dsl.rb",
    "lib/glimmer/dsl/xml/html_expression.rb",
    "lib/glimmer/dsl/xml/meta_expression.rb",
    "lib/glimmer/dsl/xml/name_space_expression.rb",
    "lib/glimmer/dsl/xml/node_parent_expression.rb",
    "lib/glimmer/dsl/xml/tag_expression.rb",
    "lib/glimmer/dsl/xml/text_expression.rb",
    "lib/glimmer/dsl/xml/xml_expression.rb",
    "lib/glimmer/error.rb",
    "lib/glimmer/invalid_keyword_error.rb",
    "lib/glimmer/opal/label.rb",
    "lib/glimmer/opal/shell.rb",
    "lib/glimmer/xml/depth_first_search_iterator.rb",
    "lib/glimmer/xml/name_space_visitor.rb",
    "lib/glimmer/xml/node.rb",
    "lib/glimmer/xml/node_visitor.rb",
    "lib/glimmer/xml/xml_visitor.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/glimmer-dsl-css".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.6".freeze
  s.summary = "Glimmer DSL for CSS".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<glimmer>.freeze, ["~> 0.9.0"])
      s.add_development_dependency(%q<rspec-mocks>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<puts_debuggerer>.freeze, ["~> 0.8.1"])
      s.add_development_dependency(%q<rake>.freeze, [">= 10.1.0", "< 14.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 2.3.9", "< 3.0.0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 6.2.1", "< 7.0.0"])
    else
      s.add_dependency(%q<glimmer>.freeze, ["~> 0.9.0"])
      s.add_dependency(%q<rspec-mocks>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<puts_debuggerer>.freeze, ["~> 0.8.1"])
      s.add_dependency(%q<rake>.freeze, [">= 10.1.0", "< 14.0.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 2.3.9", "< 3.0.0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 6.2.1", "< 7.0.0"])
    end
  else
    s.add_dependency(%q<glimmer>.freeze, ["~> 0.9.0"])
    s.add_dependency(%q<rspec-mocks>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<puts_debuggerer>.freeze, ["~> 0.8.1"])
    s.add_dependency(%q<rake>.freeze, [">= 10.1.0", "< 14.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 2.3.9", "< 3.0.0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 6.2.1", "< 7.0.0"])
  end
end

